# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('DATE', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('TMAX', models.FloatField()),
                ('TMIN', models.FloatField()),
            ],
            options={
                'verbose_name': 'Historical',
                'verbose_name_plural': 'Historical',
            },
        ),
    ]
